name: madp
channels:
  - pytorch
  - nvidia        # remove this if you use CPU-only
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.1.2
  - pytorch-cuda=12.1         # replace with  cpuonly  if no GPU
  - shapely>=2.0
  - numpy
  - pandas
  - pip
  - pip:
      - nuplan-devkit==1.2.2
      - git+https://github.com/bhyang/diffusion-es.git@main
      - git+https://github.com/AIR-THU/V2X-Graph.git@main
      - pytorch-lightning==2.2.3
      - hydra-core==1.3.2
